### ISSUE TITLE
Request: Upgrade dmn-js to the last version

### ISSUE THREAD

**Issue by rbatllet** [bpmn-io/bower-dmn-js#2]
Is there any chance to upgrade to the latest version of dmn-js (currently v1.2) in the short term?

**Comment by nikku** [comment]
We'll discontinue our pre-packaged bower releases with the next stable (`dmn-js@2`).

As part of bpmn-io/dmn-js#291 we'll offer a better alternative based on #unpkg. Cf. [bpmn-js release blog post](https://bpmn.io/blog/posts/2018-bpmn-js-0-27.html) for context and details.
